@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

abstract class Command {
# String param
# Ui ui
+ {abstract} execute() : String
+ isRunning() : boolean
}

AddCommand --|> Command
EditCommand --|> Command
FindCommand --|> Command
Command <|- HelpCommand
Command <|- ListCommand
Command <|-- WorkloadBalanceCommand
Command <|-- WorkloadForCommand
Command <|-- WorkloadSummaryCommand
DeleteCourse -|> Command
ExitCommand -|> Command
Command <|--- SavePlanCommand
Command <|--- SwitchPlanCommand
Command <|--- DeletePlanCommand
Command <|--- InvalidCommand

@enduml