@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

CourseList "courses " --> "*" Course

class CourseList {
-String planName
+add(Course course)
+deleteCourseByCode(String code) : boolean
+setEditedParams(String[] editedParams, Course course) : Course
+getCourses() : ArrayList<Course>
+isEmpty() : boolean
+clear()
+toStoreFormat() : String
}

@enduml