@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

CourseManager "ui  " --> "1 " Ui
CourseManager ..> Course

class CourseManager {
-String FILEPATH
-loadCourseFile() : InputStream
+jsonToCourse(String jsonString) : Course
+courseToJson(Course course) : String
+ifDefined(String code) : boolean
+getCourse(String code) : Course
}

@enduml