@startuml
hide circle
skinparam classAttributeIconSize 0
class Course {
    - static boolean[] dummies
    - static final int DUMMYSIZE
    - String code
    - String title
    - int mc
    - boolean offerInSem1
    - boolean offerInSem2
    - int takeInSem
    - int takeInYear

    + Course(String code, String title, int mc, int takeInYear, int takeInSem)
    + Course(String code, int mc, int takeInYear, int takeInSem)
    + static Course createDummyCourse(int mc, int takeInYear, int takeInSem)
    + String toStoreFormat()
    + static boolean isDummyFull()
    + static boolean isValidDummyIndex(int number)
    + static int getAvailableDummyIndex()
    + static void dummyInitialiseCheck(CourseList list)
}

class CourseList {
    + List<Course> getCourses()
}
Course --> CourseList : uses
@enduml
