@startuml
'https://plantuml.com/sequence-diagram

[-> "c:AddCommand" : execute(courses, parser)
activate "c:AddCommand"

"c:AddCommand" -> ":Parser": parseCourse(param)
activate ":Parser"
":Parser" --> "c:AddCommand": newCourse
deactivate ":Parser"

note left
    A loop here throws
    CEGStudyBuddyException
    if the course is a duplicate.
end note

"c:AddCommand" -> "courses:CourseList": add(newCourse)
activate "courses:CourseList"
"courses:CourseList" --> "c:AddCommand"
deactivate "courses:CourseList"

"c:AddCommand" -> ":UndoManager": recordAdd(newCourse)
activate ":UndoManager"
":UndoManager" --> "c:AddCommand"
deactivate ":UndoManager"

[<-- "c:AddCommand" : output
deactivate "c:AddCommand"

@enduml